apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 4
  
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: dev
spec:
  ports:
    - nodePort: 30100
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: webapp
  type: NodePort