apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 4
  
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30150
      